/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stacksandqueues;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Stack stackOne = new Stack();
        stackOne.push("order");
        stackOne.push("in");
        stackOne.push("be");
        stackOne.push("should");
        stackOne.push("test");

        System.out.println(stackOne.pop());
        System.out.println(stackOne.pop());
        System.out.println(stackOne.pop());
        System.out.println(stackOne.peek());
        System.out.println(stackOne.pop());
//        System.out.println(stackOne.peek());
        System.out.println(stackOne.isEmpty());
        System.out.println(stackOne);

        Queue queueOne = new Queue();
        queueOne.enQueue("new");
        queueOne.enQueue("queue");
        queueOne.enQueue("please");
        queueOne.enQueue("Matt");
        System.out.println(queueOne.deQueue());
        System.out.println(queueOne.deQueue());
        System.out.println(queueOne.deQueue());
        System.out.println(queueOne.deQueue());
        System.out.println(queueOne.isEmpty());
        System.out.println(queueOne.peek());



        System.out.println(queueOne);

//        System.out.println(queueOne.toString());


    }
}
