/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

public class App {

    public static void main(String[] args) {

        try{
            LinkedList linkList = new LinkedList();
            linkList.insert(34536);
            System.out.println(linkList.toString());

            linkList.insert(56785679);
            linkList.insert("world");
            linkList.insert("hello");
            linkList.includes(34536);


//            boolean result = linkList.includes(3);
            System.out.println(linkList.toString());
//            System.out.println(linkList.includes("1234"));

        }catch(Exception e){
            System.out.println(e);
        }

    }
}


