/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenges2;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        String expectedOutput = "something";
        String actualOutput = Library.someLibraryMethod();
        assertEquals("someLibraryMethod should return 'true'", expectedOutput, actualOutput);
    }
}
