/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stacksandqueues;

import org.junit.Test;
import org.junit.function.ThrowingRunnable;

import java.util.EmptyStackException;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void stackTest() {
        Stack testStack = new Stack();
        assertNull(testStack.top);
        assertTrue(testStack.isEmpty());
        testStack.push("first");
        assertNotNull(testStack.top);
        testStack.push("second");
        testStack.push("third");
        String actual = testStack.toString();
        System.out.println(testStack);
        String expected = "{third}->{second}->{first}->";
        assertEquals(expected, actual);
        Object actual2 = testStack.pop();
        Object expected2 = "third";
        assertEquals(expected2, actual2);
        testStack.pop();
        testStack.pop();
        assertTrue(testStack.isEmpty());
    }
    @Test public void queueTest(){
        Queue testQueue = new Queue();
        assertNull(testQueue.front);
        testQueue.enQueue("first");
        assertNotNull(testQueue.front);
        testQueue.enQueue("second");
        testQueue.enQueue("third");
        testQueue.enQueue("fourth");
        System.out.println(testQueue);
        String expected = "{first}->{second}->{third}->{fourth}->";
        String actual = testQueue.toString();
        assertEquals(expected, actual);
        Object expected2 = "first";
        Object actual2 = testQueue.deQueue();
        assertEquals(expected2, actual2);
        Object expected3 = "second";
        Object actual3 = testQueue.peek();
        assertEquals(expected3, actual3);
        testQueue.deQueue();
        testQueue.deQueue();
        testQueue.deQueue();
        assertNull(testQueue.front);
        System.out.println(testQueue);

    }
}
