/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenges2;

public class Library {
    public static String someLibraryMethod() {
        return "something";
    }
}
